language: node_js
sudo: false
cache:
  npm: true
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
node_js:
  - 12
  - 10
  - 8
os: osx
git:
  depth: 3
install:
  - npm install
script:
  - npm run lint
  - npm run test:ci
  - npm run test:coverage:ci
  - sonar-scanner
addons:
  sonarcloud:
    organization: 'sagar-gavhane'
    token:
      secure: '9274a1e302d50acb6d40ea6bcccad149e2b4d0ed'
